package zidanJmartKD;

public enum ProductCategory
{
    BOOK, KITCHEN, ELECTRONIC, FASHION, GAMING, GADGET, MOTHERCARE, 
    COSMETICS, HEALTHCARE, FURNITURE, JEWELRY, TOYS, FNB, STATIONERY,
    SPORTS, AUTMOTIVE, PETCARE, ART_CRAFT, CARPENTRY, MISCELLANEOUS,
    PROPERTY, TRAVEL, WEDDING;
}
